language: php
php:
  - '7.1'
services:
  - postgresql
env:
  global:
    - APP_ENV=testing
    - dbadmin=postgres
    - defaultdb=postgres
    - dbname=laravelprjtest
    - dbuser=laravelprjtest
    - dbpass=laravelprjtest
before_script:
  - composer install
  - psql -U $dbadmin -c "CREATE ROLE $dbuser WITH LOGIN PASSWORD '$dbpass'" $defaultdb
  - psql -U $dbadmin -c "CREATE DATABASE $dbname OWNER $dbuser" $defaultdb
  - ./artisan migrate:reset
  - ./artisan migrate
after_success:
  - vendor/bin/php-coveralls --verbose
  - cat /home/travis/build/knaka/laravelprj/build/logs/coveralls-upload.json
