language: php
php:
  - '7.1'
services:
  - postgresql
env:
  global:
    - APP_ENV=testing
    - dbname=laravelprjtest
    - dbuser=laravelprjtest
    - dbpass=laravelprjtest
before_script:
  - composer install
  - createdb laravelprjtest
  - psql -U postgres -c "CREATE ROLE $dbuser WITH LOGIN PASSWORD '$dbpass'" postgres
  - psql -U postgres -c "CREATE DATABASE $dbname OWNER $dbuser" postgres
  - ./artisan migrate:reset
  - ./artisan migrate
after_success:
  - vendor/bin/php-coveralls --verbose
